### ISSUE TITLE
Create a skeleton terraform provider

### ISSUE THREAD

**Issue by httpoz** [useless-solutions/terraform-provider-statsig#3]
# Overview

In order to establish a baseline for a proper Terraform Provider, we need to create the skeleton layout and minimum required configurations.

These are listed below under **Acceptance Criteria**.
Additional information and tools are included as well, such as publishing, documenting, and general tutorials.

# Acceptance Criteria

- [x] Copy the scaffolding repo listed below and use that as a baseline
- [x] Create an `index.md` document at the root, as per [Documenting Providers](https://developer.hashicorp.com/terraform/registry/providers/docs)
- [x] Create a `terraform-registry-manifest.json` file at the root, as per [Terraform Registry Manifest File](https://developer.hashicorp.com/terraform/registry/providers/publishing#terraform-registry-manifest-file)

# Relevant Information

## Initial Steps/Requirements

- [How to build a provider – Video](https://www.youtube.com/watch?v=2BvpqmFpchI)
- [Terraform Plugin Framework tutorials](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework)
- [Implement a provider with the Terraform Plugin Framework](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework/providers-plugin-framework-provider)

## References

- [Terraform Plugin Framework](https://developer.hashicorp.com/terraform/plugin/framework)
- [Terraform Plugin Framework tutorials](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework)
- [Writing a Provider](https://developer.hashicorp.com/terraform/registry/providers/publishing#writing-a-provider)

## Repository Naming

> [!IMPORTANT]
>
> In order to be detected by the Terraform Registry, all provider repositories on GitHub must match the pattern `terraform-provider-{NAME}`, and the repository must be public. Only lowercase repository names are supported.

-- We are okay here already, with `terraform-provider-statsig`

## Tools

- [Terraform Registry Doc Preview Tool](https://registry.terraform.io/tools/doc-preview)
- [terraform-provider-scaffolding-framework](https://github.com/hashicorp/terraform-provider-scaffolding-framework)

**Comment by tamirarnesty** [comment]
The [terraform-provider-scaffolding-framework](https://github.com/hashicorp/terraform-provider-scaffolding-framework) repo gets cloned and renamed to our project, but it comes with a lot already setup, which is great.

This includes:

- `terraform-registry-manifest.json` file
- `.md` files with examples for various resources
- some `docs` structure, including an `index.md`

**Comment by tamirarnesty** [comment]
The initial scaffolding was created and merged in #4, but there are still some modifications to make to the template to suit out Statsig needs.

This involves:

1. Implementing the [initial `Provider` type](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework/providers-plugin-framework-provider#implement-initial-provider-type)
2. Implementing the [provider server](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework/providers-plugin-framework-provider#implement-the-provider-server)
3. Testing a [provider install](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework/providers-plugin-framework-provider#prepare-terraform-for-local-provider-install) and validating the resource is correctly referenced

**Comment by tamirarnesty** [comment]
> Create an `index.md` document at the root, as per [Documenting Providers](https://developer.hashicorp.com/terraform/registry/providers/docs)

The `index.md` file actually falls under `docs/`, but alas. The same.
