### ISSUE TITLE
Create `tags` Resource

### ISSUE THREAD

**Issue by httpoz** [useless-solutions/terraform-provider-statsig#6]
# Overview

As the first resource being created, there is additional setup that's needed in order to finish the task.

Along with the `tags` _data source_ (`"READ"`) and _resource_ (`"CREATE"`), the API will need to be setup to make requests. Since the basics are to create and read data, the first operations should be `Get` and `Post` requests.

# Acceptance Criteria

- [x] Create an initial `Get` request function that can accept generic query parameters as a Map
  - Might be changed later to a custom struct that is subclasses by different objects, but tbd
- [x] Create base `doRequest` and `buildRequest` functions, similar to the existing provider's implementation
> [!NOTE]
> This is common amongst Terraform Provider implementations.
> Reference:
> - Existing Statsig Provider: [buildRequest](https://github.com/statsig-io/terraform-provider-statsig/blob/8cdd8017b5967be4f54b0384bd26a3c0310f12a0/internal/transport.go#L88-L114), [doRequest](https://github.com/statsig-io/terraform-provider-statsig/blob/8cdd8017b5967be4f54b0384bd26a3c0310f12a0/internal/transport.go#L58-L86)
> - HashiCups (example that goes with the provider Tutorial): [client.go](https://github.com/hashicorp-demoapp/hashicups-client-go/blob/1dc072ac97e2575c5191ee32a2dd9946fb4a7718/client.go#L66-L91)

> [!WARNING]
> Will likely modify this once things are more stable and we have more info on the query params and `POST`/`UPDATE` requests.

- [ ] Create an initial `Post` request function that includes a request body
- [x] Create `TagsDataSource` – this will read all tags at once, as per the [API](https://docs.statsig.com/console-api/tags#get-/tags)
- [ ] Create `TagResource`

# Relevant Information

## References

- [`tags` Console API ref](https://docs.statsig.com/console-api/tags)

**Comment by tamirarnesty** [comment]
To create a `DataSource`, Providers use an implementation of the `datasource.DataSource` interface type as the starting point for a resource implementation.

This interface requires the following:

1. **Metadata method**. This defines the data source type name, which is how the data source is referred to in Terraform configurations.
2. **Schema method**. This defines the schema for any data source configuration and state data.
3. **Read method**. This defines the logic which sets the Terraform state for the data source.
